### ISSUE TITLE
按组一同注册命令的关键词 内容 权限

### ISSUE THREAD

**Issue by axty666** [nonebot/nonebot#300]
**功能描述**
按组一同注册命令的关键词 内容 权限

**理由**
对于那些群内自动回答问题的bot来说，命令过多导致过多的使用 `@on_command`一类的 管理起来十分的繁琐。不如列出一种方式来加载一组指定好关键词 发送的内容 

**实现方案**

1. 写一个格式一致的文件 例如 `command.yml`
``` yaml
Faq: 
- Command: 
    FirstKey: '123' # @on_command
    Aliases: '456' 
    Send: '789'
    Keywords:  # @on_natural_language
      - '123'
      - '456'
- Command: 
    FirstKey: 'abc'
    Send: 'hello'
    Permission: 
      BanQQ: 
        - '123456'
        - '456798'
```
2. 读取出来 比如说
``` python
import yaml
def load_yaml():
    with open('command.yml', 'r', encoding='utf_8') as talk:
        result = yaml.load((talk.read()), Loader=yaml.FullLoader)
        return result
```
3.  在插件里面调用 `load_yaml()`函数，并将其读出来的按照每一个列表里面所包含的内容进行注册命令 响应时例如：
```
1. 我：123
    bot：789
2. (123456)：abc

```
